### ISSUE TITLE
Kint output is hidden behind z-indexed and fixed content

### ISSUE THREAD

**Issue by vatavale** [kint-php/kint#181]
I try to make simple changes in CSS, but with no results yet.

**Comment by raveren** [comment]
You can `<?php -ddd($variable) ?>` to clear output before dump and halt execution after it. Catering global Kint css to rare use cases is not the way to go unfortunately.

**Comment by vatavale** [comment]
Ok. Thank you for advice.
BTW I have bring Kint to front by adding:

``` css
.kint {
    z-index:999;
    position: relative;
}

in kint/view/base.less
```
