### ISSUE TITLE
Theme CSS redesign

### ISSUE THREAD

**Issue by raveren** [kint-php/kint#95]
- [x] Apply border box sizing to all themes, as it's becoming de-facto standart and not only is easier to style, but messes Kint themes when output displayed directly on page (like ajax output)

``` css

*,
*:before,
*:after {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
}
```
- [ ] Create a theme to be as bare-bones as possible to still remain readable as a base for theme authors, alter base LESS files to be as generic as possible.
- [ ] ~~Remove all magic numbers from main LESS files, use variables everywhere (mostly based on `@spacing` ratio)~~
- [ ] Separate `@spacing` and `@scale` LESS variables
- [x] Research best fonts on all platforms to fall back on to prevent the fugly "Courier New" as much as possible (see http://www.codediesel.com/tools/easy-php-debugging-with-kint/) 
- [ ] Create sprite for 
  - open in new window
  - close ajax
  - check all in ajax
  - clear checked
  - resend ajax call

**Comment by dhazelett** [comment]
FWIW while it is becoming standard to use `box-sizing: border-box;`, it may be safer as a third party to only do something like:

``` less
.kint * {
    &, &:after, &:before {
        box-sizing: border-box;
    }
}
```

Another thing to keep in mind as pointed out by Paul Irish, is not to use `*` to set the `border-box` but instead set it to `inherit`. That way all you'd need to do is

``` css
.kint {
   box-sizing: border-box;
}
```

Edit: forgot the [link](http://www.paulirish.com/2012/box-sizing-border-box-ftw/) to Paul's article.

**Comment by raveren** [comment]
Hello :)

The current css is already generated by:

``` less
.kint,
.kint::before,
.kint::after,
.kint *,
.kint *::before,
.kint *::after {
  box-sizing    : border-box;
  border-radius : 0;
  color         : @text-color;
  float         : none !important;
  font-family   : Consolas, Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono, Bitstream Vera Sans Mono, Courier New, monospace, serif;
  line-height   : 15px;
  margin        : 0;
  padding       : 0;
  text-align    : left;
}
```

This issue was just a note-to-self, I'm closing it and migrating to my internal notes now, thanks :)
